urls.py
from django.urls import path
from . import views

app_name = 'medication'

urlpatterns = [
    path('meds/<int:pk>', views.MedicationsList.as_view(), name='meds-list'),
    #path('meds/create/', views.MedicationCreate.as_view(), name='meds-create'),
    path('meds/create/<int:pk>', views.MedicationCreate.as_view(), name='meds-create'),
    path('meds/<int:pk>/update', views.MedicationUpdate.as_view(), name='meds-update'),
    path('meds/<int:pk>/delete', views.MedicationDelete.as_view(), name='meds-delete'),
]

models.py
from django.db import models
from geriatrics.models import Admission
from django.conf import settings

SHIFT = (
        ('0', '6am-6pm'),
        ('1', '6pm-6am'),
        ('2', '6am-2pm'),
        ('3', '2pm-10pm'),
        ('4', '10pm-6am'),
        )

# Create your models here.
class Drug(models.Model):
    generic_name = models.CharField(max_length=200, db_index=True)
    brand_name = models.CharField(max_length=200, blank=True)
    dosage = models.CharField(max_length=70, blank=True)

    class Meta:
        ordering = ['generic_name']
        verbose_name = 'Medication'
        verbose_name_plural = 'Medications'

    def __str__(self):
        if self.brand_name and self.dosage:
            return f'{self.generic_name} ({self.brand_name}) {self.dosage}'
        elif self.brand_name:
            return f'{self.generic_name} ({self.brand_name})'
        elif self.dosage:
            return f'{self.generic_name} {self.dosage}'
        else:
            return f'{self.generic_name}'

class Medication(models.Model):
    created = models.DateField(auto_now_add=True, editable=False, null=False, blank=False)
    last_modified = models.DateField(auto_now=True, editable=False, null=False, blank=False)
    date_ordered = models.DateField(auto_now=False)
    admission = models.ForeignKey(Admission, on_delete=models.CASCADE, limit_choices_to={'discharged': False}) 
    drug = models.ForeignKey(Drug, on_delete=models.CASCADE, verbose_name='Medication', null=True, blank=False)
    frequency = models.CharField(max_length=70, blank=True)
    route = models.CharField(max_length=70, blank=True)
    discontinued = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date_ordered']
        verbose_name = 'Medication order'
        verbose_name_plural = 'Medication orders'

    def __str__(self):
        return u'{}: {}'.format(self.admission.resident, self.drug)

class TimeToBeGiven(models.Model):
    medication = models.ForeignKey(Medication,
                              related_name='order',
                              on_delete=models.CASCADE)
    time_given = models.TimeField(auto_now=False, null=False, blank=False)

    class Meta:
        ordering = ['medication']
        verbose_name = 'Time given'
        verbose_name_plural = 'Times given'

    def __str__(self):
        return f'{self.medication} - {self.time_given.strftime("%-I:%M %p")}'

class MedicationSheet(models.Model):
    date = models.DateField(auto_now=False)
    shift = models.CharField(max_length=1, choices=SHIFT, blank=True) 
    nurse = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return f'{self.date} {self.get_shift_display()}-{self.nurse}'

class MedicationGiven(models.Model):
    medication_sheet = models.ForeignKey(MedicationSheet, on_delete=models.CASCADE)
    medication = models.ForeignKey(Medication, on_delete=models.CASCADE)
    time_given = models.TimeField(auto_now=False, null=False, blank=False)

    class Meta:
        verbose_name_plural = 'Medications given'

    def __str__(self):
        return f'"{self.medication}" Given: {self.time_given}'

forms.py
from django import forms
from .models import Medication
from bootstrap_modal_forms.forms import BSModalModelForm

class DateInput(forms.DateInput):
    input_type = 'date'

class MedicationCreateForm(BSModalModelForm):
    class Meta:
        model = Medication
        widgets = { 'date_ordered': DateInput(), }
        exclude = ('discontinued',)

views.py
from django.views.generic import ListView
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import Medication
from .forms import MedicationCreateForm
from geriatrics.models import Admission

from .tables import MedicationTable

from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalDeleteView

class MedicationsList(LoginRequiredMixin, ListView):
    model = Medication
    template_name = 'medication/includes/medications.html'

    def get_context_data(self, *args, **kwargs):
        request = self.request
        context = super(MedicationsList, self).get_context_data(**kwargs)
        if 'pk' in self.kwargs:
            try:
                admission = Admission.objects.get(id=self.kwargs['pk'])
                data = Medication.objects.filter(admission=admission)
                if data:
                    meds_table = MedicationTable(data)
                    meds_table.paginate(page=request.GET.get("page", 1), per_page=5)
                    context['table'] = meds_table
                else:
                    context['table'] = None
            except Admission.DoesNotExist:
                pass
        return context

class MedicationCreate(LoginRequiredMixin, BSModalCreateView):
    model = Medication 
    form_class = MedicationCreateForm
    success_message = 'Medication order was created.'
    success_url = reverse_lazy('geriatrics:admissions')

    def get_form(self, *args, **kwargs):
        form = super(MedicationCreate, self).get_form(*args, **kwargs)
        if 'pk' in self.kwargs:
            try:
                admission = Admission.objects.get(id=self.kwargs['pk'])
                form.fields['admission'].initial = admission
                self.success_url = reverse_lazy('geriatrics:admission-detail', kwargs={'pk': admission.id,})
            except Admission.DoesNotExist:
                pass
        return form

    def get_context_data(self, **kwargs):
        context = super(MedicationCreate, self).get_context_data(**kwargs)
        context['title'] = 'Create Medication'
        context['btn'] = 'Create'
        return context

class MedicationUpdate(LoginRequiredMixin, BSModalUpdateView):
    model = Medication
    form_class = MedicationCreateForm
    template_name = 'medication/medication_form.html'
    success_message = 'Medication order was updated.'
    success_url = reverse_lazy('geriatrics:admissions')

    def get_object(self, *args, **kwargs):
        meds = super(MedicationUpdate, self).get_object(*args, **kwargs)
        admission = meds.admission
        #added_by = self.request.user
        self.success_url = reverse_lazy('geriatrics:admission-detail', kwargs={'pk': admission.id,})
        return meds 

    def get_context_data(self, **kwargs):
        context = super(MedicationUpdate, self).get_context_data(**kwargs)
        context['title'] = 'Update Medication'
        context['btn'] = 'Update'
        return context

class MedicationDelete(LoginRequiredMixin, BSModalDeleteView):
    model = Medication
    success_message = 'Medication oder deleted.'
    success_url = reverse_lazy('geriatrics:admissions')

    def get_object(self, *args, **kwargs):
        meds = super(MedicationDelete, self).get_object(*args, **kwargs)
        admission = meds.admission
        self.success_url = reverse_lazy('geriatrics:admission-detail', kwargs={'pk': admission.id,})
        return meds 

templates/medication/includes/medications.html
{% if table %}
  {% load django_tables2 %}
  {% render_table table %}
{% else %}
  <div class="alert alert-dismissible alert-info fade show">
    <button type="button" class="close">&times;</button>
    <h4 class="alert-heading">Heads up!</h4>
    <p class="mb-0">No medications to show. <a href="{% url 'medication_admin:index' %}" class="alert-link">Create</a> one now.</p>
  </div>
{% endif %}

<script type="text/javascript">
$(document).ready(function() {
    const medsUpdate = $(this).find('.update-meds');
    const medsDelete = $(this).find('.delete-meds');
    
    medsUpdate.each(function () {
      $(this).modalForm({formURL: $(this).attr('href'), modalID: "#management-modal"});
      $(this).removeAttr('href');
    }); 
    
    medsDelete.each(function () {
      $(this).modalForm({formURL: $(this).attr('href'), modalID: "#management-modal"});
      $(this).removeAttr('href');
    });
});
</script>

templates/medication/medication_confirm_delete.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete Medication Order</h3>
    <button type="button" class="close" data-mdb-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p>Are you sure you want to delete Medication Order of
      <strong>{{ medication }}{% if medication.frequency %} {{ medication.frequency }}{% endif %}</strong>?</p>
  </div>

  <div class="modal-footer">
  {% if perms.medication.delete_medication %}
    <button type="submit" class="btn btn-danger">Delete</button>
  {% else %}
    <a class="btn btn-danger disabled">Delete</a>
  {% endif %}
  </div>

</form>

templates/medication/medication_form.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}
  <div class="modal-header">
    <h3 class="modal-title">{{ title }}</h3>
    <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
    {% if perms.medication.change_medication %}
      <button type="submit" class="btn btn-primary">{{ btn }}</button>
    {% else %}
      <a class="btn btn-primary disabled">{{ btn }}</a>
    {% endif %}  
  </div>
</form>